# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-20 12:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_auto_20180314_2025'),
        ('check', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='checks',
            name='check_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user.AddUser'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='checks',
            name='check_status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='check.CheckStatus'),
        ),
    ]
