# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-20 12:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('check', '0002_auto_20180320_2005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checks',
            name='check_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.User'),
        ),
    ]
