# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-01 08:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_create', models.DateTimeField(auto_created=True)),
                ('user_name', models.CharField(max_length=1024)),
                ('user_phone', models.CharField(max_length=1024)),
                ('user_id_number', models.CharField(max_length=1024)),
                ('user_sex', models.BooleanField(choices=[(0, '男'), (1, '女')], default=0)),
                ('user_id_img_1', models.CharField(max_length=1024)),
                ('user_id_img_2', models.CharField(max_length=1024)),
                ('user_img', models.CharField(max_length=1024)),
                ('check_status', models.CharField(max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='Root',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('root_name', models.CharField(max_length=1024)),
                ('root_type', models.CharField(max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_create', models.DateTimeField(auto_created=True)),
                ('user_name', models.CharField(max_length=1024)),
                ('user_phone', models.CharField(max_length=1024)),
                ('user_id_number', models.CharField(max_length=1024)),
                ('user_sex', models.BooleanField(default=True)),
                ('user_id_img_1', models.CharField(max_length=1024)),
                ('user_id_img_2', models.CharField(max_length=1024)),
                ('user_img', models.CharField(max_length=1024)),
                ('user_salary', models.IntegerField(default=1250)),
                ('user_display', models.BooleanField(default=True)),
                ('user_level', models.IntegerField(default=50)),
            ],
        ),
        migrations.CreateModel(
            name='UserBaoXian',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bx_create', models.DateTimeField(auto_created=True)),
                ('bx_type', models.CharField(max_length=1024)),
                ('bx_third_party', models.CharField(max_length=1024)),
                ('bx_time', models.DateTimeField()),
                ('bx_number', models.CharField(max_length=1024, null=True)),
                ('bx_img', models.CharField(max_length=1024, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='user_baoxian',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.UserBaoXian'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Projects'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_root',
            field=models.ManyToManyField(to='user.Root'),
        ),
        migrations.AddField(
            model_name='adduser',
            name='user_check',
            field=models.ManyToManyField(to='user.User'),
        ),
    ]
