# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-01 08:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adduser',
            name='check_status',
            field=models.CharField(blank=True, max_length=1024),
        ),
        migrations.AlterField(
            model_name='adduser',
            name='user_check',
            field=models.ManyToManyField(blank=True, null=True, to='user.User'),
        ),
        migrations.AlterField(
            model_name='adduser',
            name='user_create',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
