# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-02 02:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20180301_1717'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_passwd',
            field=models.CharField(default='123', max_length=1024),
        ),
    ]
