# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-07 04:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_user_user_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_type', models.CharField(max_length=10240)),
                ('check_info', models.CharField(max_length=102400)),
            ],
        ),
        migrations.RemoveField(
            model_name='adduser',
            name='user_check',
        ),
        migrations.AddField(
            model_name='adduser',
            name='check_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user.CheckType'),
            preserve_default=False,
        ),
    ]
