# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-07 13:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_auto_20180307_1200'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adduser',
            name='check_type',
        ),
        migrations.AddField(
            model_name='checktype',
            name='check_note',
            field=models.CharField(default=1, max_length=102400),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='checktype',
            name='check_info',
            field=models.CharField(max_length=10240),
        ),
    ]
