# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-14 09:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_auto_20180307_2118'),
    ]

    operations = [
        migrations.CreateModel(
            name='Checks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_info', models.IntegerField()),
                ('check_id', models.CharField(max_length=1024)),
                ('check_note', models.CharField(max_length=102400)),
            ],
        ),
        migrations.CreateModel(
            name='CheckStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_status', models.CharField(max_length=1024)),
            ],
        ),
        migrations.RenameField(
            model_name='checktype',
            old_name='check_info',
            new_name='type_name',
        ),
        migrations.RemoveField(
            model_name='adduser',
            name='check_status',
        ),
        migrations.RemoveField(
            model_name='checktype',
            name='check_note',
        ),
        migrations.RemoveField(
            model_name='checktype',
            name='check_type',
        ),
        migrations.AddField(
            model_name='checks',
            name='check_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.CheckStatus'),
        ),
        migrations.AddField(
            model_name='checks',
            name='check_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.CheckType'),
        ),
    ]
