# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-02-18 07:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IndexGlobalSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProjectName', models.CharField(default='无名称设置名称', max_length=1024)),
                ('ProjectColor', models.CharField(default='#409EFF', max_length=1024)),
                ('ProjectIcon', models.CharField(default='None', max_length=1024)),
            ],
        ),
    ]
