# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-02-19 16:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_childitem_sidaitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='childitem',
            name='To',
            field=models.CharField(max_length=1024),
        ),
    ]
