# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-02-19 17:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_auto_20180220_0016'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SidaItem',
            new_name='SideItem',
        ),
    ]
